server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    # Always false to prevent unexpected db changes
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_ACCESS_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  file:
    name: ./logs/auth-service.log